import { useState, useEffect } from "react";
import Products from "../../components/Products";
import Categories from "../../components/Categories";
import Navbar from "../../components/Navbar";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Home({ productsData, categoriesData }) {
  const [products, setProducts] = useState(productsData);
  const [filters, setFilters] = useState([]);

  useEffect(() => {
    if (filters.length !== 0) {
      let productsByCategory = productsData.filter((x) =>
        filters.includes(x.category)
      );
      setProducts(productsByCategory);
    } else {
      return setProducts(productsData);
    }
  }, [filters]);

  function filterFunc(category) {
    if (filters.includes(category)) {
      setFilters((prev) => prev.filter((x) => x !== category));
    } else {
      setFilters((prev) => [...prev, category]);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>FakeStore</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <div className={styles.campaign}></div>
        <Categories categories={categoriesData} filterFunc={filterFunc} />
        <Products products={products} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const categoriesres = await fetch(
    "https://fakestoreapi.com/products/categories"
  );
  const categoriesData = await categoriesres.json();
  const productsres = await fetch("https://fakestoreapi.com/products");
  const productsData = await productsres.json();

  if (!productsData || !categoriesData) return { notFound: true };

  return {
    props: {
      productsData,
      categoriesData,
    },
  };
}
